name: Initial setup

on:
  push:

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    if: "!github.event.repository.is_template"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update files
        run: |-
          PARSER_NAME="${REPO_NAME#tree-sitter-}"
          printf 'PARSER_NAME=%s\n' "$PARSER_NAME" >> "$GITHUB_ENV"
          if [[ -n $AUTHOR_EMAIL && ${AUTHOR_EMAIL#*@} != users.noreply.github.com ]]; then
            AUTHOR_NAME="$AUTHOR_NAME <$AUTHOR_EMAIL>"
          fi
          grep -rl PARSER_NAME | xargs sed "s/PARSER_NAME/$PARSER_NAME/g" -i
          grep -rl AUTHOR_NAME | xargs sed "s/AUTHOR_NAME/$AUTHOR_NAME/g" -i
          if [[ $REPO_OWNER != tree-sitter-grammars ]]; then
            grep --exclude-dir=.github/workflows -rl tree-sitter-grammars | \
              xargs sed "s/tree-sitter-grammars/$REPO_OWNER/g" -i
          fi
          rm .github/workflows/setup.yml
        env:
          REPO_OWNER: ${{github.repository_owner}}
          REPO_NAME: ${{github.event.repository.name}}
          AUTHOR_NAME: ${{github.event.head_commit.author.name}}
          AUTHOR_EMAIL: ${{github.event.head_commit.author.email}}
      - name: Update repository details
        run: |-
          gh repo edit \
            --enable-merge-commit=false \
            --enable-discussions=false \
            --enable-projects=false \
            --enable-wiki=false \
            --add-topic='tree-sitter' \
            --add-topic='parser' \
            --add-topic="$PARSER_NAME" \
            -d "${REPO_DESC:-$PARSER_NAME grammar for tree-sitter}"
        env:
          REPO_DESC: ${{github.event.repository.description}}
      - name: Update commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: ${{github.event.head_commit.author.username}}
          commit_user_email: ${{github.event.head_commit.author.email}}
          commit_message: Initial commit
          commit_options: --amend
          push_options: --force
          skip_fetch: true
